/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ProductHunt {
        "compact": boolean;
        "product": string;
        "schema": 'dark' | 'light';
        "token": string;
    }
}
declare global {
    interface HTMLProductHuntElement extends Components.ProductHunt, HTMLStencilElement {
    }
    var HTMLProductHuntElement: {
        prototype: HTMLProductHuntElement;
        new (): HTMLProductHuntElement;
    };
    interface HTMLElementTagNameMap {
        "product-hunt": HTMLProductHuntElement;
    }
}
declare namespace LocalJSX {
    interface ProductHunt {
        "compact"?: boolean;
        "product"?: string;
        "schema"?: 'dark' | 'light';
        "token"?: string;
    }
    interface IntrinsicElements {
        "product-hunt": ProductHunt;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "product-hunt": LocalJSX.ProductHunt & JSXBase.HTMLAttributes<HTMLProductHuntElement>;
        }
    }
}
